-- =============================================================================
-- SECTIONAL TESTS & QUESTIONS SCHEMA FOR SUPABASE
-- Education Concept Sectional Test System
-- =============================================================================

-- 1. Create sectional_tests table
CREATE TABLE IF NOT EXISTS sectional_tests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  subject TEXT NOT NULL,
  total_questions INTEGER DEFAULT 0,
  total_marks NUMERIC NOT NULL DEFAULT 50,
  duration_minutes INTEGER NOT NULL DEFAULT 20,
  negative_marking NUMERIC NOT NULL DEFAULT 0.25,
  published BOOLEAN DEFAULT true,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sec_tests_subj ON sectional_tests(subject);
CREATE INDEX IF NOT EXISTS idx_sec_tests_pub ON sectional_tests(published);

-- 2. Create sectional_questions table
CREATE TABLE IF NOT EXISTS sectional_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_id BIGINT NOT NULL REFERENCES sectional_tests(id) ON DELETE CASCADE,
  question_order INTEGER NOT NULL DEFAULT 1,
  question_text TEXT NOT NULL,
  option_a TEXT NOT NULL,
  option_b TEXT NOT NULL,
  option_c TEXT NOT NULL,
  option_d TEXT NOT NULL,
  correct_option VARCHAR(2) NOT NULL, -- 'A', 'B', 'C', 'D'
  explanation TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sec_questions_test ON sectional_questions(test_id);
CREATE INDEX IF NOT EXISTS idx_sec_questions_order ON sectional_questions(test_id, question_order);

-- 3. Row Level Security (RLS)
ALTER TABLE sectional_tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE sectional_questions ENABLE ROW LEVEL SECURITY;

-- sectional_tests policies
DROP POLICY IF EXISTS "Public select sectional_tests" ON sectional_tests;
DROP POLICY IF EXISTS "Admin insert sectional_tests" ON sectional_tests;
DROP POLICY IF EXISTS "Admin update sectional_tests" ON sectional_tests;
DROP POLICY IF EXISTS "Admin delete sectional_tests" ON sectional_tests;

CREATE POLICY "Public select sectional_tests" ON sectional_tests 
  FOR SELECT USING (published = true OR public.is_admin());

CREATE POLICY "Admin insert sectional_tests" ON sectional_tests 
  FOR INSERT WITH CHECK (public.is_admin());

CREATE POLICY "Admin update sectional_tests" ON sectional_tests 
  FOR UPDATE USING (public.is_admin());

CREATE POLICY "Admin delete sectional_tests" ON sectional_tests 
  FOR DELETE USING (public.is_admin());

-- sectional_questions policies
-- Students can only select questions for published tests (or if admin)
DROP POLICY IF EXISTS "Public select sectional_questions" ON sectional_questions;
DROP POLICY IF EXISTS "Admin insert sectional_questions" ON sectional_questions;
DROP POLICY IF EXISTS "Admin update sectional_questions" ON sectional_questions;
DROP POLICY IF EXISTS "Admin delete sectional_questions" ON sectional_questions;

CREATE POLICY "Public select sectional_questions" ON sectional_questions 
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM sectional_tests 
      WHERE sectional_tests.id = sectional_questions.test_id 
      AND (sectional_tests.published = true OR public.is_admin())
    )
  );

CREATE POLICY "Admin insert sectional_questions" ON sectional_questions 
  FOR INSERT WITH CHECK (public.is_admin());

CREATE POLICY "Admin update sectional_questions" ON sectional_questions 
  FOR UPDATE USING (public.is_admin());

CREATE POLICY "Admin delete sectional_questions" ON sectional_questions 
  FOR DELETE USING (public.is_admin());

-- 4. Auto-update timestamps trigger
CREATE OR REPLACE FUNCTION update_sectional_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_sectional_tests_modtime ON sectional_tests;
CREATE TRIGGER update_sectional_tests_modtime
  BEFORE UPDATE ON sectional_tests
  FOR EACH ROW EXECUTE FUNCTION update_sectional_modified_column();

DROP TRIGGER IF EXISTS update_sectional_questions_modtime ON sectional_questions;
CREATE TRIGGER update_sectional_questions_modtime
  BEFORE UPDATE ON sectional_questions
  FOR EACH ROW EXECUTE FUNCTION update_sectional_modified_column();

-- =============================================================================
-- 5. sectional_test_results table (Latest Result per student per test)
-- =============================================================================

CREATE TABLE IF NOT EXISTS sectional_test_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_id BIGINT NOT NULL REFERENCES sectional_tests(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  score NUMERIC NOT NULL DEFAULT 0,
  total_marks NUMERIC NOT NULL DEFAULT 50,
  correct_answers INTEGER NOT NULL DEFAULT 0,
  incorrect_answers INTEGER NOT NULL DEFAULT 0,
  unattempted_answers INTEGER NOT NULL DEFAULT 0,
  accuracy NUMERIC NOT NULL DEFAULT 0,
  negative_marks NUMERIC NOT NULL DEFAULT 0,
  time_taken_seconds INTEGER NOT NULL DEFAULT 0,
  answers JSONB NOT NULL DEFAULT '{}'::jsonb,
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT uq_sectional_test_user UNIQUE (test_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_sec_test_results_user ON sectional_test_results(user_id);
CREATE INDEX IF NOT EXISTS idx_sec_test_results_test ON sectional_test_results(test_id);

ALTER TABLE sectional_test_results ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users select own sectional_test_results" ON sectional_test_results;
DROP POLICY IF EXISTS "Users insert own sectional_test_results" ON sectional_test_results;
DROP POLICY IF EXISTS "Users update own sectional_test_results" ON sectional_test_results;
DROP POLICY IF EXISTS "Admin delete sectional_test_results" ON sectional_test_results;

CREATE POLICY "Users select own sectional_test_results" ON sectional_test_results
  FOR SELECT USING (auth.uid() = user_id OR public.is_admin());

CREATE POLICY "Users insert own sectional_test_results" ON sectional_test_results
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users update own sectional_test_results" ON sectional_test_results
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Admin delete sectional_test_results" ON sectional_test_results
  FOR DELETE USING (public.is_admin());

DROP TRIGGER IF EXISTS update_sectional_test_results_modtime ON sectional_test_results;
CREATE TRIGGER update_sectional_test_results_modtime
  BEFORE UPDATE ON sectional_test_results
  FOR EACH ROW EXECUTE FUNCTION update_sectional_modified_column();
