-- -----------------------------------------------------------------------------
-- SECURE ADMIN SCHEMA MIGRATION: PHASE A (EC NOTES / CONTENT MANAGEMENT)
-- This script provisions backend tables for the content management modules while
-- enforcing strict Row Level Security (RLS) using the public.is_admin() function.
-- -----------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. TABLE DEFINITIONS

CREATE TABLE IF NOT EXISTS paid_ebooks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  price NUMERIC NOT NULL,
  file_path TEXT NOT NULL,
  file_name TEXT,
  file_size BIGINT,
  cover_image_path TEXT,
  published BOOLEAN DEFAULT true,
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_paid_ebooks_pub ON paid_ebooks(published);

CREATE TABLE IF NOT EXISTS free_ebooks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  file_path TEXT NOT NULL,
  file_name TEXT,
  file_size BIGINT,
  cover_image_path TEXT,
  published BOOLEAN DEFAULT true,
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_free_ebooks_pub ON free_ebooks(published);

CREATE TABLE IF NOT EXISTS current_affairs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  file_path TEXT NOT NULL,
  file_name TEXT,
  file_size BIGINT,
  published BOOLEAN DEFAULT true,
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_current_affairs_pub ON current_affairs(published);

CREATE TABLE IF NOT EXISTS exam_patterns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_category TEXT NOT NULL,
  exam_name TEXT NOT NULL,
  pattern_file_path TEXT,
  syllabus_file_path TEXT,
  published BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_exam_patterns_pub ON exam_patterns(published);

CREATE TABLE IF NOT EXISTS study_resources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  file_path TEXT NOT NULL,
  file_name TEXT,
  file_size BIGINT,
  published BOOLEAN DEFAULT true,
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_study_resources_pub ON study_resources(published);

CREATE TABLE IF NOT EXISTS banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section TEXT NOT NULL,
  image_path TEXT NOT NULL,
  link_url TEXT,
  display_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_banners_act ON banners(is_active);

CREATE TABLE IF NOT EXISTS top_recommendations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_type TEXT NOT NULL,
  content_id BIGINT NOT NULL,
  display_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_top_rec_act ON top_recommendations(is_active);

CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. MODIFIED TIMESTAMP TRIGGERS

CREATE OR REPLACE FUNCTION update_phase_a_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

DO $$
DECLARE
    t text;
BEGIN
    FOR t IN SELECT unnest(ARRAY['paid_ebooks', 'free_ebooks', 'current_affairs', 'exam_patterns', 'study_resources', 'banners', 'top_recommendations', 'app_settings'])
    LOOP
        EXECUTE format('
            DROP TRIGGER IF EXISTS update_%I_modtime ON %I;
            CREATE TRIGGER update_%I_modtime
            BEFORE UPDATE ON %I
            FOR EACH ROW EXECUTE FUNCTION update_phase_a_modified_column();
        ', t, t, t, t);
    END LOOP;
END;
$$;

-- 3. ENABLE RLS

ALTER TABLE paid_ebooks ENABLE ROW LEVEL SECURITY;
ALTER TABLE free_ebooks ENABLE ROW LEVEL SECURITY;
ALTER TABLE current_affairs ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_patterns ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE top_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;

-- 4. APPLY RLS POLICIES

-- PAID EBOOKS
DROP POLICY IF EXISTS "Public select paid_ebooks" ON paid_ebooks;
DROP POLICY IF EXISTS "Admin insert paid_ebooks" ON paid_ebooks;
DROP POLICY IF EXISTS "Admin update paid_ebooks" ON paid_ebooks;
DROP POLICY IF EXISTS "Admin delete paid_ebooks" ON paid_ebooks;
CREATE POLICY "Public select paid_ebooks" ON paid_ebooks FOR SELECT USING (published = true OR public.is_admin());
CREATE POLICY "Admin insert paid_ebooks" ON paid_ebooks FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "Admin update paid_ebooks" ON paid_ebooks FOR UPDATE USING (public.is_admin());
CREATE POLICY "Admin delete paid_ebooks" ON paid_ebooks FOR DELETE USING (public.is_admin());

-- FREE EBOOKS
DROP POLICY IF EXISTS "Public select free_ebooks" ON free_ebooks;
DROP POLICY IF EXISTS "Admin insert free_ebooks" ON free_ebooks;
DROP POLICY IF EXISTS "Admin update free_ebooks" ON free_ebooks;
DROP POLICY IF EXISTS "Admin delete free_ebooks" ON free_ebooks;
CREATE POLICY "Public select free_ebooks" ON free_ebooks FOR SELECT USING (published = true OR public.is_admin());
CREATE POLICY "Admin insert free_ebooks" ON free_ebooks FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "Admin update free_ebooks" ON free_ebooks FOR UPDATE USING (public.is_admin());
CREATE POLICY "Admin delete free_ebooks" ON free_ebooks FOR DELETE USING (public.is_admin());

-- CURRENT AFFAIRS
DROP POLICY IF EXISTS "Public select current_affairs" ON current_affairs;
DROP POLICY IF EXISTS "Admin insert current_affairs" ON current_affairs;
DROP POLICY IF EXISTS "Admin update current_affairs" ON current_affairs;
DROP POLICY IF EXISTS "Admin delete current_affairs" ON current_affairs;
CREATE POLICY "Public select current_affairs" ON current_affairs FOR SELECT USING (published = true OR public.is_admin());
CREATE POLICY "Admin insert current_affairs" ON current_affairs FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "Admin update current_affairs" ON current_affairs FOR UPDATE USING (public.is_admin());
CREATE POLICY "Admin delete current_affairs" ON current_affairs FOR DELETE USING (public.is_admin());

-- EXAM PATTERNS
DROP POLICY IF EXISTS "Public select exam_patterns" ON exam_patterns;
DROP POLICY IF EXISTS "Admin insert exam_patterns" ON exam_patterns;
DROP POLICY IF EXISTS "Admin update exam_patterns" ON exam_patterns;
DROP POLICY IF EXISTS "Admin delete exam_patterns" ON exam_patterns;
CREATE POLICY "Public select exam_patterns" ON exam_patterns FOR SELECT USING (published = true OR public.is_admin());
CREATE POLICY "Admin insert exam_patterns" ON exam_patterns FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "Admin update exam_patterns" ON exam_patterns FOR UPDATE USING (public.is_admin());
CREATE POLICY "Admin delete exam_patterns" ON exam_patterns FOR DELETE USING (public.is_admin());

-- STUDY RESOURCES
DROP POLICY IF EXISTS "Public select study_resources" ON study_resources;
DROP POLICY IF EXISTS "Admin insert study_resources" ON study_resources;
DROP POLICY IF EXISTS "Admin update study_resources" ON study_resources;
DROP POLICY IF EXISTS "Admin delete study_resources" ON study_resources;
CREATE POLICY "Public select study_resources" ON study_resources FOR SELECT USING (published = true OR public.is_admin());
CREATE POLICY "Admin insert study_resources" ON study_resources FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "Admin update study_resources" ON study_resources FOR UPDATE USING (public.is_admin());
CREATE POLICY "Admin delete study_resources" ON study_resources FOR DELETE USING (public.is_admin());

-- BANNERS
DROP POLICY IF EXISTS "Public select banners" ON banners;
DROP POLICY IF EXISTS "Admin insert banners" ON banners;
DROP POLICY IF EXISTS "Admin update banners" ON banners;
DROP POLICY IF EXISTS "Admin delete banners" ON banners;
CREATE POLICY "Public select banners" ON banners FOR SELECT USING (is_active = true OR public.is_admin());
CREATE POLICY "Admin insert banners" ON banners FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "Admin update banners" ON banners FOR UPDATE USING (public.is_admin());
CREATE POLICY "Admin delete banners" ON banners FOR DELETE USING (public.is_admin());

-- TOP RECOMMENDATIONS
DROP POLICY IF EXISTS "Public select top_recommendations" ON top_recommendations;
DROP POLICY IF EXISTS "Admin insert top_recommendations" ON top_recommendations;
DROP POLICY IF EXISTS "Admin update top_recommendations" ON top_recommendations;
DROP POLICY IF EXISTS "Admin delete top_recommendations" ON top_recommendations;
CREATE POLICY "Public select top_recommendations" ON top_recommendations FOR SELECT USING (is_active = true OR public.is_admin());
CREATE POLICY "Admin insert top_recommendations" ON top_recommendations FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "Admin update top_recommendations" ON top_recommendations FOR UPDATE USING (public.is_admin());
CREATE POLICY "Admin delete top_recommendations" ON top_recommendations FOR DELETE USING (public.is_admin());

-- APP SETTINGS
DROP POLICY IF EXISTS "Public select app_settings" ON app_settings;
DROP POLICY IF EXISTS "Admin insert app_settings" ON app_settings;
DROP POLICY IF EXISTS "Admin update app_settings" ON app_settings;
DROP POLICY IF EXISTS "Admin delete app_settings" ON app_settings;
CREATE POLICY "Public select app_settings" ON app_settings FOR SELECT USING (key = 'whatsapp_number' OR public.is_admin());
CREATE POLICY "Admin insert app_settings" ON app_settings FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "Admin update app_settings" ON app_settings FOR UPDATE USING (public.is_admin());
CREATE POLICY "Admin delete app_settings" ON app_settings FOR DELETE USING (public.is_admin());

