-- =============================================================================
-- CHAPTER WISE TESTS SCHEMA FOR SUPABASE
-- Education Concept Chapter Wise Test System
-- =============================================================================

-- 1. Create chapters table
CREATE TABLE IF NOT EXISTS chapters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject TEXT NOT NULL,
  sub_category TEXT,
  name TEXT NOT NULL,
  hindi_name TEXT,
  description TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Backward compatibility migration if table already exists
ALTER TABLE chapters ADD COLUMN IF NOT EXISTS sub_category TEXT;

CREATE INDEX IF NOT EXISTS idx_chapters_subj ON chapters(subject);
CREATE INDEX IF NOT EXISTS idx_chapters_sub_cat ON chapters(sub_category);
CREATE INDEX IF NOT EXISTS idx_chapters_sort ON chapters(sort_order);

-- 2. Create chapter_tests table
CREATE TABLE IF NOT EXISTS chapter_tests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chapter_id BIGINT NOT NULL REFERENCES chapters(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  subject TEXT NOT NULL,
  total_questions INTEGER DEFAULT 0,
  total_marks NUMERIC NOT NULL DEFAULT 50,
  duration_minutes INTEGER NOT NULL DEFAULT 20,
  negative_marking NUMERIC NOT NULL DEFAULT 0.25,
  published BOOLEAN DEFAULT true,
  sort_order INTEGER DEFAULT 0,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chap_tests_chap ON chapter_tests(chapter_id);
CREATE INDEX IF NOT EXISTS idx_chap_tests_subj ON chapter_tests(subject);
CREATE INDEX IF NOT EXISTS idx_chap_tests_pub ON chapter_tests(published);
CREATE INDEX IF NOT EXISTS idx_chap_tests_sort ON chapter_tests(sort_order);

-- 3. Create chapter_questions table
CREATE TABLE IF NOT EXISTS chapter_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_id BIGINT NOT NULL REFERENCES chapter_tests(id) ON DELETE CASCADE,
  question_order INTEGER NOT NULL DEFAULT 1,
  question_text TEXT NOT NULL,
  option_a TEXT NOT NULL,
  option_b TEXT NOT NULL,
  option_c TEXT NOT NULL,
  option_d TEXT NOT NULL,
  correct_option VARCHAR(2) NOT NULL, -- 'A', 'B', 'C', 'D'
  explanation TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chap_questions_test ON chapter_questions(test_id);
CREATE INDEX IF NOT EXISTS idx_chap_questions_order ON chapter_questions(test_id, question_order);

-- 4. Create chapter_test_results table
CREATE TABLE IF NOT EXISTS chapter_test_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_id BIGINT NOT NULL REFERENCES chapter_tests(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  score NUMERIC NOT NULL DEFAULT 0,
  total_marks NUMERIC NOT NULL DEFAULT 50,
  correct_answers INTEGER NOT NULL DEFAULT 0,
  incorrect_answers INTEGER NOT NULL DEFAULT 0,
  unattempted_answers INTEGER NOT NULL DEFAULT 0,
  accuracy NUMERIC NOT NULL DEFAULT 0,
  negative_marks NUMERIC NOT NULL DEFAULT 0,
  time_taken_seconds INTEGER NOT NULL DEFAULT 0,
  answers JSONB NOT NULL DEFAULT '{}'::jsonb,
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT uq_chapter_test_user UNIQUE (test_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_chap_test_results_user ON chapter_test_results(user_id);
CREATE INDEX IF NOT EXISTS idx_chap_test_results_test ON chapter_test_results(test_id);

-- 5. Row Level Security (RLS)
ALTER TABLE chapters ENABLE ROW LEVEL SECURITY;
ALTER TABLE chapter_tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE chapter_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE chapter_test_results ENABLE ROW LEVEL SECURITY;

-- chapters policies
DROP POLICY IF EXISTS "Public select chapters" ON chapters;
DROP POLICY IF EXISTS "Admin insert chapters" ON chapters;
DROP POLICY IF EXISTS "Admin update chapters" ON chapters;
DROP POLICY IF EXISTS "Admin delete chapters" ON chapters;

CREATE POLICY "Public select chapters" ON chapters FOR SELECT USING (true);
CREATE POLICY "Admin insert chapters" ON chapters FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "Admin update chapters" ON chapters FOR UPDATE USING (public.is_admin());
CREATE POLICY "Admin delete chapters" ON chapters FOR DELETE USING (public.is_admin());

-- chapter_tests policies
DROP POLICY IF EXISTS "Public select chapter_tests" ON chapter_tests;
DROP POLICY IF EXISTS "Admin insert chapter_tests" ON chapter_tests;
DROP POLICY IF EXISTS "Admin update chapter_tests" ON chapter_tests;
DROP POLICY IF EXISTS "Admin delete chapter_tests" ON chapter_tests;

CREATE POLICY "Public select chapter_tests" ON chapter_tests 
  FOR SELECT USING (published = true OR public.is_admin());
CREATE POLICY "Admin insert chapter_tests" ON chapter_tests 
  FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "Admin update chapter_tests" ON chapter_tests 
  FOR UPDATE USING (public.is_admin());
CREATE POLICY "Admin delete chapter_tests" ON chapter_tests 
  FOR DELETE USING (public.is_admin());

-- chapter_questions policies
DROP POLICY IF EXISTS "Public select chapter_questions" ON chapter_questions;
DROP POLICY IF EXISTS "Admin insert chapter_questions" ON chapter_questions;
DROP POLICY IF EXISTS "Admin update chapter_questions" ON chapter_questions;
DROP POLICY IF EXISTS "Admin delete chapter_questions" ON chapter_questions;

CREATE POLICY "Public select chapter_questions" ON chapter_questions 
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM chapter_tests 
      WHERE chapter_tests.id = chapter_questions.test_id 
      AND (chapter_tests.published = true OR public.is_admin())
    )
  );
CREATE POLICY "Admin insert chapter_questions" ON chapter_questions 
  FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "Admin update chapter_questions" ON chapter_questions 
  FOR UPDATE USING (public.is_admin());
CREATE POLICY "Admin delete chapter_questions" ON chapter_questions 
  FOR DELETE USING (public.is_admin());

-- chapter_test_results policies
DROP POLICY IF EXISTS "Users select own chapter_test_results" ON chapter_test_results;
DROP POLICY IF EXISTS "Users insert own chapter_test_results" ON chapter_test_results;
DROP POLICY IF EXISTS "Users update own chapter_test_results" ON chapter_test_results;
DROP POLICY IF EXISTS "Admin delete chapter_test_results" ON chapter_test_results;

CREATE POLICY "Users select own chapter_test_results" ON chapter_test_results
  FOR SELECT USING (auth.uid() = user_id OR public.is_admin());
CREATE POLICY "Users insert own chapter_test_results" ON chapter_test_results
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own chapter_test_results" ON chapter_test_results
  FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Admin delete chapter_test_results" ON chapter_test_results
  FOR DELETE USING (public.is_admin());

-- 6. Trigger for updated_at timestamps
CREATE OR REPLACE FUNCTION update_chapter_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_chapters_modtime ON chapters;
CREATE TRIGGER update_chapters_modtime
  BEFORE UPDATE ON chapters
  FOR EACH ROW EXECUTE FUNCTION update_chapter_modified_column();

DROP TRIGGER IF EXISTS update_chapter_tests_modtime ON chapter_tests;
CREATE TRIGGER update_chapter_tests_modtime
  BEFORE UPDATE ON chapter_tests
  FOR EACH ROW EXECUTE FUNCTION update_chapter_modified_column();

DROP TRIGGER IF EXISTS update_chapter_questions_modtime ON chapter_questions;
CREATE TRIGGER update_chapter_questions_modtime
  BEFORE UPDATE ON chapter_questions
  FOR EACH ROW EXECUTE FUNCTION update_chapter_modified_column();

DROP TRIGGER IF EXISTS update_chapter_test_results_modtime ON chapter_test_results;
CREATE TRIGGER update_chapter_test_results_modtime
  BEFORE UPDATE ON chapter_test_results
  FOR EACH ROW EXECUTE FUNCTION update_chapter_modified_column();
